### ISSUE TITLE
Database is not updated on nextcloud

### ISSUE THREAD

**Issue by PsychoD** [MiKeePass/MiKee#3]
Current version: Testflight 1.1.0 (7)

Observed behavior / Reproduce: 
1. Open MiKee
2. Open Database from Nextcloud (Nextcloud app needs to be installed and configured!)
3. Change/create an entry
4. Close MiKee
5. Open Nextcloud App
6. Observe: Password Database file is unchanged. 

Expected: 
6. Password Database file is updated.

**Comment by maxep** [comment]
Thanks for the report! I can reproduce and I will have a look.

**Comment by maxep** [comment]
It has been fixed in 1.1.0 (8)
Please re-open if you are still having the issue.
